WitherSoundRange: 128         #凋灵生成声音半径
EnderDragonSoundRange: 512    #末影龙死亡声音半径
trigger_welcome_message: ">>点击欢迎新玩家 %name%<<"
db_host: '127.0.0.1'
db_port: 3306
db_user: "root"
db_passwd: "TccServer2024@"
db_database: "neotcc_tools"
# 使用tpa命令所需的游玩时间
tpa_play_time_requirement: 12
# 新玩家可以使用back的时间
back_play_time_for_new_players: 12